/* Copyright(C) 2024-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * channels.ts: Client-side JavaScript generator for the PrismCast channels subtab.
 */

export function generateChannelsSubtabScript(): string {

  return [
    "<script>",
    "(function() {",

    // Channels subtab switching function. Scoped to .channels-subtab-btn / .channels-subtab-panel to avoid colliding with Config tab subtabs.
    "  function switchChannelsSubtab(subtab, updateUrl) {",
    "    var btns = document.querySelectorAll('.channels-subtab-btn');",
    "    var panels = document.querySelectorAll('.channels-subtab-panel');",
    "    for(var i = 0; i < btns.length; i++) {",
    "      btns[i].classList.remove('active');",
    "      btns[i].setAttribute('aria-selected', 'false');",
    "      if(btns[i].getAttribute('data-channels-subtab') === subtab) {",
    "        btns[i].classList.add('active');",
    "        btns[i].setAttribute('aria-selected', 'true');",
    "      }",
    "    }",
    "    for(var j = 0; j < panels.length; j++) {",
    "      panels[j].classList.remove('active');",
    "      if(panels[j].id === 'channels-subtab-' + subtab) {",
    "        panels[j].classList.add('active');",
    "      }",
    "    }",
    "    try { localStorage.setItem('prismcast-channels-subtab', subtab); } catch(e) {}",
    "    if(updateUrl !== false) {",
    "      var newHash = (subtab === 'channels') ? '#channels' : '#channels/' + subtab;",
    "      if(window.location.hash !== newHash) {",
    "        window.location.hash = newHash;",
    "      }",
    "    }",
    "  }",

    // Expose for main tab script hashchange handler.
    "  window.switchChannelsSubtab = switchChannelsSubtab;",

    // Attach click handlers to channels subtab buttons.
    "  var btns = document.querySelectorAll('.channels-subtab-btn');",
    "  for(var i = 0; i < btns.length; i++) {",
    "    btns[i].addEventListener('click', function() {",
    "      switchChannelsSubtab(this.getAttribute('data-channels-subtab'));",
    "    });",
    "  }",

    // Delete a user profile with confirmation.
    "  window.deleteUserProfile = function(key) {",
    "    if(!confirm('Delete profile \"' + key + '\" and all its domain mappings?')) return;",
    "    fetch('/config/profiles/' + encodeURIComponent(key), { method: 'DELETE' })",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        if(data.success) { location.reload(); }",
    "        else { showToast('Failed to delete profile: ' + (data.error || 'Unknown error.'), 'error'); }",
    "      })",
    "      .catch(function() { showToast('Failed to delete profile.', 'error'); });",
    "  };",

    // Edit an existing user profile by pre-populating the wizard.
    "  window.editUserProfile = function(key) {",
    "    fetch('/config/profiles')",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        if(!data.success) { showToast('Failed to load profiles.', 'error'); return; }",
    "        var profiles = data.profiles || [];",
    "        var match = profiles.find(function(p) { return p.key === key; });",
    "        if(!match || !match.profile) { showToast('Profile not found.', 'error'); return; }",
    "        var p = match.profile;",
    "        var editCs = p.channelSelection || {};",
    "        var strat = editCs.strategy || 'none';",
    "        var strategyFields = {};",
    "        var editStrat = window.__wizardStrategies.find(function(st) { return st.id === strat; });",
    "        if(editStrat) {",
    "          for(var i = 0; i < editStrat.fields.length; i++) {",
    "            var ef = editStrat.fields[i];",
    "            if(ef.type === 'text' && editCs[ef.id]) { strategyFields[ef.id] = editCs[ef.id]; }",
    "            else if(ef.type === 'boolean' && editCs[ef.id]) { strategyFields[ef.id] = true; }",
    "          }",
    "        }",
    "        var flags = {};",
    "        var wizFlags = window.__wizardFlags;",
    "        for(var i = 0; i < wizFlags.length; i++) { if(p[wizFlags[i].id]) flags[wizFlags[i].id] = true; }",
    "        var domains = (match.domains && match.domains.length > 0) ?",
    "          match.domains.map(function(d) { return { domain: d.domain, provider: d.provider || '', providerTag: d.providerTag || '' }; }) :",
    "          [{ domain: '', provider: '', providerTag: '' }];",
    "        wizardState = {",
    "          currentStep: 1, editKey: key, editMode: true, highestStep: 5, profileName: key,",
    "          baseProfile: p.extends || '', strategy: strat,",
    "          strategyFields: strategyFields, flags: flags,",
    "          hideSelector: p.hideSelector || '', domains: domains, description: p.description || ''",
    "        };",
    "        var title = document.getElementById('wizard-title');",
    "        if(title) title.textContent = 'Edit Provider Profile';",
    "        document.getElementById('wizard-modal').style.display = 'flex';",
    "        renderWizardStep();",
    "      })",
    "      .catch(function() { showToast('Failed to load profile data.', 'error'); });",
    "  };",

    // Pending import data stored while the import preview modal is open.
    "  var pendingImportData = null;",

    // Import a provider pack via file picker — shows a preview modal before importing.
    "  window.startProviderImport = function() {",
    "    var input = document.createElement('input');",
    "    input.type = 'file';",
    "    input.accept = '.json,application/json';",
    "    input.onchange = function() {",
    "      if(!input.files || !input.files[0]) return;",
    "      var reader = new FileReader();",
    "      reader.onload = function() {",
    "        try {",
    "          var data = JSON.parse(reader.result);",
    "          pendingImportData = data;",
    "          var profileCount = data.profiles ? Object.keys(data.profiles).length : 0;",
    "          var domainCount = data.domains ? Object.keys(data.domains).length : 0;",
    "          var channelCount = data.channels ? Object.keys(data.channels).length : 0;",
    "          var html = '<table class=\"import-summary-table\">';",
    "          html += '<tr><td class=\"import-summary-label\">Pack name</td>';",
    "          html += '<td>' + esc(data.name || 'Unnamed') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Profiles</td>';",
    "          html += '<td>' + plural(profileCount, 'profile') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Domains</td>';",
    "          html += '<td>' + plural(domainCount, 'domain') + '</td></tr>';",
    "          html += '<tr><td class=\"import-summary-label\">Channels</td>';",
    "          html += '<td>' + plural(channelCount, 'channel') + '</td></tr>';",
    "          html += '</table>';",
    "          if(channelCount > 0) {",
    "            html += '<div class=\"export-divider\"></div>';",
    "            html += '<label class=\"export-option-label\">';",
    "            html += '<input type=\"checkbox\" id=\"import-include-channels\" checked> Include ' + plural(channelCount, 'channel') + '</label>';",
    "            html += '<div class=\"export-hint\">Import the channel definitions from this pack. Uncheck to import only the provider profiles and domains.</div>';",
    "          }",
    "          document.getElementById('import-modal-body').innerHTML = html;",
    "          document.getElementById('import-modal').style.display = 'flex';",
    "        } catch(e) {",
    "          showToast('Invalid JSON file.', 'error');",
    "        }",
    "      };",
    "      reader.readAsText(input.files[0]);",
    "    };",
    "    input.click();",
    "  };",

    // Close the import preview modal.
    "  window.closeImportModal = function() {",
    "    document.getElementById('import-modal').style.display = 'none';",
    "    pendingImportData = null;",
    "  };",

    // Execute the import after the user confirms in the preview modal.
    "  window.executeImport = function() {",
    "    if(!pendingImportData) return;",
    "    var skipChannels = false;",
    "    var cb = document.getElementById('import-include-channels');",
    "    if(cb && !cb.checked) skipChannels = true;",
    "    var body = Object.assign({}, pendingImportData);",
    "    if(skipChannels) body.skipChannels = true;",
    "    fetch('/config/profiles/import', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify(body)",
    "    })",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(result) {",
    "        closeImportModal();",
    "        if(result.success) {",
    "          var msg = 'Imported ' + plural(result.summary.profilesAdded, 'profile') + ', ' +",
    "            plural(result.summary.domainsAdded, 'domain') + ', ' + plural(result.summary.channelsAdded, 'channel') + '.';",
    "          if(result.warnings && result.warnings.length > 0) msg += ' Warnings: ' + result.warnings.join('; ');",
    "          showToast(msg, 'success');",
    "          location.reload();",
    "        } else {",
    "          showToast('Import failed: ' + (result.error || 'Unknown error.'), 'error');",
    "        }",
    "      })",
    "      .catch(function() { closeImportModal(); showToast('Import request failed.', 'error'); });",
    "  };",

    // Export a provider pack. Opens a modal with profile checklist and options. Shows provider name prominently for each profile with domain and channel counts.
    // The select-all row is hidden when there is only one profile since the single checkbox makes it redundant.
    "  window.startProviderExport = function() {",
    "    fetch('/config/profiles')",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        var profiles = data.profiles || [];",
    "        if(profiles.length === 0) { showToast('No user profiles to export.', 'error'); return; }",
    "        var listDiv = document.getElementById('export-profile-list');",
    "        var html = '';",
    "        for(var i = 0; i < profiles.length; i++) {",
    "          var p = profiles[i];",
    "          var domainCount = p.domains ? p.domains.length : 0;",
    "          var channelCount = p.channelCount || 0;",
    "          var providerName = '';",
    "          for(var di = 0; di < (p.domains || []).length; di++) {",
    "            if(p.domains[di].provider) { providerName = p.domains[di].provider; break; }",
    "          }",
    "          var meta = [];",
    "          if(providerName) meta.push(esc(providerName));",
    "          meta.push(plural(domainCount, 'domain'));",
    "          meta.push(plural(channelCount, 'channel'));",
    "          html += '<label class=\"export-profile-item\">';",
    "          html += '<input type=\"checkbox\" class=\"export-profile-cb\" value=\"' + esc(p.key) + '\" checked>';",
    "          html += '<div class=\"export-profile-info\">';",
    "          html += '<div class=\"export-profile-name\">' + esc(p.key) + '</div>';",
    "          html += '<div class=\"export-profile-meta\">' + meta.join(' &middot; ') + '</div>';",
    "          html += '</div></label>';",
    "        }",
    "        listDiv.innerHTML = html;",
    "        document.getElementById('export-select-all').checked = true;",
    "        document.getElementById('export-select-all-row').style.display = (profiles.length > 1) ? '' : 'none';",
    "        document.getElementById('export-include-channels').checked = false;",
    "        document.getElementById('export-modal').style.display = 'flex';",
    "      })",
    "      .catch(function() { showToast('Failed to load profiles.', 'error'); });",
    "  };",

    // Toggle all export profile checkboxes.
    "  window.toggleExportAll = function(master) {",
    "    var cbs = document.querySelectorAll('.export-profile-cb');",
    "    for(var i = 0; i < cbs.length; i++) cbs[i].checked = master.checked;",
    "  };",

    // Close the export modal.
    "  window.closeExportModal = function() {",
    "    document.getElementById('export-modal').style.display = 'none';",
    "  };",

    // Execute the export by building the download URL from the selected profiles.
    "  window.executeExport = function() {",
    "    var cbs = document.querySelectorAll('.export-profile-cb:checked');",
    "    if(cbs.length === 0) { showToast('Select at least one profile.', 'error'); return; }",
    "    var keys = [];",
    "    for(var i = 0; i < cbs.length; i++) keys.push(cbs[i].value);",
    "    var url = '/config/profiles/export?profile=' + encodeURIComponent(keys.join(',')) + '&domains=1';",
    "    if(document.getElementById('export-include-channels').checked) url += '&channels=1';",
    "    closeExportModal();",
    "    window.location.href = url;",
    "  };",

    // Profile builder wizard state and rendering. highestStep tracks the furthest step the user has reached, allowing click-to-navigate back to visited steps.
    "  var wizardState = {",
    "    currentStep: 1,",
    "    editKey: null,",
    "    editMode: false,",
    "    highestStep: 1,",
    "    profileName: '',",
    "    baseProfile: '',",
    "    strategy: 'none',",
    "    strategyFields: {},",
    "    flags: {},",
    "    hideSelector: '',",
    "    domains: [{ domain: '', provider: '', providerTag: '' }],",
    "    description: ''",
    "  };",

    // Auto-generate a provider tag from a provider name: lowercase, strip non-alphanumeric.
    "  function autoProviderTag(name) {",
    "    return name.toLowerCase().replace(/[^a-z0-9]/g, '');",
    "  }",

    // HTML-escape user input for safe innerHTML insertion in the review step.
    "  function esc(str) {",
    "    var d = document.createElement('div');",
    "    d.appendChild(document.createTextNode(str || ''));",
    "    return d.innerHTML;",
    "  }",

    // Pluralization helper for UI text: returns "1 domain", "2 domains", etc.
    "  function plural(n, word) {",
    "    return n + ' ' + word + (n === 1 ? '' : 's');",
    "  }",

    // Render the current wizard step into the wizard-content area.
    "  function renderWizardStep() {",
    "    var content = document.getElementById('wizard-content');",
    "    var errDiv = document.getElementById('wizard-error');",
    "    var backBtn = document.getElementById('wizard-back');",
    "    var nextBtn = document.getElementById('wizard-next');",
    "    var saveBtn = document.getElementById('wizard-save');",
    "    var saveTestBtn = document.getElementById('wizard-save-test');",
    "    if(!content) return;",
    "    errDiv.style.display = 'none';",
    "    errDiv.textContent = '';",

    // Update step indicator. Steps up to highestStep are clickable for navigation.
    "    var steps = document.querySelectorAll('.wizard-step');",
    "    for(var i = 0; i < steps.length; i++) {",
    "      var stepNum = parseInt(steps[i].getAttribute('data-step'), 10);",
    "      steps[i].classList.remove('active', 'completed', 'clickable');",
    "      if(stepNum < wizardState.currentStep) steps[i].classList.add('completed');",
    "      if(stepNum === wizardState.currentStep) steps[i].classList.add('active');",
    "      if(stepNum !== wizardState.currentStep && stepNum <= wizardState.highestStep) steps[i].classList.add('clickable');",
    "      steps[i].onclick = (function(n) { return function() { wizardGoToStep(n); }; })(stepNum);",
    "    }",

    // Show/hide navigation buttons.
    "    backBtn.style.display = (wizardState.currentStep > 1) ? '' : 'none';",
    "    nextBtn.style.display = (wizardState.currentStep < 5) ? '' : 'none';",
    "    saveBtn.style.display = (wizardState.currentStep === 5) ? '' : 'none';",
    "    saveTestBtn.style.display = (wizardState.currentStep === 5) ? '' : 'none';",

    "    var html = '';",
    "    var s = wizardState;",

    // Step 1: Base Profile.
    "    if(s.currentStep === 1) {",
    "      html += '<div class=\"field-group\">';",
    "      html += '<label for=\"wizard-profile-name\">Profile Name</label>';",
    "      var nameReadonly = s.editMode ? ' readonly style=\"opacity: 0.6; cursor: not-allowed;\"' : '';",
    "      html += '<input type=\"text\" id=\"wizard-profile-name\" value=\"' + s.profileName.replace(/\"/g, '&quot;') +",
    "        '\" placeholder=\"e.g., myProvider\"' + nameReadonly + '>';",
    "      html += '<div class=\"field-hint\">' + (s.editMode ? 'Profile name cannot be changed.' :",
    "        'Unique identifier. Letters, numbers, and hyphens only.') + '</div>';",
    "      html += '</div>';",
    "      html += '<label>Base Profile</label>';",
    "      var profiles = window.__wizardProfiles || {};",
    "      var cats = [",
    "        { key: 'api', title: 'Fullscreen API',",
    "          desc: 'For single-channel sites that require JavaScript\\'s requestFullscreen() API instead of keyboard shortcuts.' },",
    "        { key: 'keyboard', title: 'Keyboard Fullscreen',",
    "          desc: 'For single-channel sites that use the \\'f\\' key to toggle fullscreen mode.' },",
    "        { key: 'multiChannel', title: 'Multi-Channel',",
    "          desc: 'For sites that host multiple live channels on a single page.' },",
    "        { key: 'special', title: 'Special',",
    "          desc: 'For non-standard use cases like static pages without video.' },",
    "        { key: 'custom', title: 'Custom', desc: '' }",
    "      ];",
    "      for(var ci = 0; ci < cats.length; ci++) {",
    "        var cat = cats[ci];",
    "        var items = (profiles[cat.key] || []).filter(function(p) { return !s.editMode || p.name !== s.editKey; });",
    "        if(items.length === 0) continue;",
    "        html += '<div class=\"wizard-profile-category\">';",
    "        html += '<h4>' + cat.title + '</h4>';",
    "        if(cat.desc) html += '<div class=\"wizard-category-desc\">' + esc(cat.desc) + '</div>';",
    "        for(var pi = 0; pi < items.length; pi++) {",
    "          var p = items[pi];",
    "          var checked = (s.baseProfile === p.name) ? ' checked' : '';",
    "          html += '<label class=\"wizard-profile-option\">';",
    "          html += '<input type=\"radio\" name=\"baseProfile\" value=\"' + p.name + '\"' + checked + '>';",
    "          var sumTag = p.summary ? ' <span class=\"profile-option-summary\">(' + esc(p.summary) + ')</span>' : '';",
    "          html += '<div><div class=\"profile-option-name\">' + esc(p.name) + sumTag + '</div>';",
    "          html += '<div class=\"profile-option-desc\">' + esc(p.description) + '</div></div>';",
    "          html += '</label>';",
    "        }",
    "        html += '</div>';",
    "      }",
    "    }",

    // Step 2: Channel Selection Strategy. Strategies and their fields are rendered from the server-side registry (window.__wizardStrategies).
    "    if(s.currentStep === 2) {",
    "      html += '<label>Channel Selection Strategy</label>';",
    "      var strategies = window.__wizardStrategies;",
    "      for(var si = 0; si < strategies.length; si++) {",
    "        var st = strategies[si];",
    "        var checked = (s.strategy === st.id) ? ' checked' : '';",
    "        html += '<label class=\"wizard-strategy-option\">';",
    "        html += '<input type=\"radio\" name=\"strategy\" value=\"' + st.id + '\"' + checked + '>';",
    "        html += '<div><div class=\"wizard-strategy-label\">' + st.name + '</div>';",
    "        html += '<div class=\"wizard-strategy-desc\">' + st.description + '</div></div>';",
    "        html += '</label>';",
    "      }",
    "      var currentStrat = strategies.find(function(st) { return st.id === s.strategy; });",
    "      if(currentStrat && currentStrat.fields.length > 0) {",
    "        html += '<hr style=\"border: none; border-top: 1px solid var(--border-default); margin: 16px 0;\">';",
    "        for(var fi = 0; fi < currentStrat.fields.length; fi++) {",
    "          var f = currentStrat.fields[fi];",
    "          if(f.type === 'text') {",
    "            var val = (s.strategyFields[f.id] || '').replace(/\"/g, '&quot;');",
    "            var optLabel = f.required ? '' : ' <span style=\"color: var(--text-muted);\">(optional)</span>';",
    "            html += '<div class=\"field-group\">';",
    "            html += '<label for=\"wizard-sf-' + f.id + '\">' + f.label + optLabel + '</label>';",
    "            html += '<input type=\"text\" id=\"wizard-sf-' + f.id + '\" data-field=\"' + f.id + '\" value=\"' + val + '\"';",
    "            if(f.placeholder) html += ' placeholder=\"' + f.placeholder.replace(/\"/g, '&quot;') + '\"';",
    "            html += '>';",
    "            if(f.hint) html += '<div class=\"field-hint\">' + f.hint + '</div>';",
    "            html += '</div>';",
    "          } else if(f.type === 'boolean') {",
    "            var boolChecked = s.strategyFields[f.id] ? ' checked' : '';",
    "            html += '<label class=\"wizard-flag\">';",
    "            html += '<input type=\"checkbox\" data-field=\"' + f.id + '\"' + boolChecked + '>';",
    "            html += '<div><div class=\"wizard-flag-label\">' + f.label + '</div>';",
    "            if(f.hint) html += '<div class=\"wizard-flag-desc\">' + f.hint + '</div>';",
    "            html += '</div></label>';",
    "          }",
    "        }",
    "      }",
    "    }",

    // Step 3: Override Flags. Flags are rendered from the server-side registry (window.__wizardFlags).
    "    if(s.currentStep === 3) {",
    "      html += '<label>Profile Flags</label>';",
    "      html += '<div class=\"field-hint\" style=\"margin-bottom: 12px;\">These override the base profile. ' +",
    "        'Only change what differs from ' + s.baseProfile + '.</div>';",
    "      var wizFlags = window.__wizardFlags;",
    "      for(var fi = 0; fi < wizFlags.length; fi++) {",
    "        var f = wizFlags[fi];",
    "        var checked = s.flags[f.id] ? ' checked' : '';",
    "        html += '<label class=\"wizard-flag\">';",
    "        html += '<input type=\"checkbox\" name=\"flag-' + f.id + '\"' + checked + '>';",
    "        html += '<div><div class=\"wizard-flag-label\">' + f.label + '</div>';",
    "        html += '<div class=\"wizard-flag-desc\">' + f.description + '</div></div>';",
    "        html += '</label>';",
    "      }",
    "      html += '<div class=\"field-group\" style=\"margin-top: 12px;\">';",
    "      html += '<label for=\"wizard-hide-selector\">Hide Selector (CSS) <span style=\"color: var(--text-muted);\">(optional)</span></label>';",
    "      html += '<input type=\"text\" id=\"wizard-hide-selector\" value=\"' + s.hideSelector.replace(/\"/g, '&quot;') +",
    "        '\" placeholder=\"e.g., .overlay, .ad-banner\">';",
    "      html += '<div class=\"field-hint\">Overlay elements to hide during capture.</div>';",
    "      html += '</div>';",
    "    }",

    // Step 4: Domain Mapping.
    "    if(s.currentStep === 4) {",
    "      html += '<label>Domain Mapping</label>';",
    "      html += '<div class=\"field-hint\" style=\"margin-bottom: 12px;\">Map a streaming site domain to this profile.</div>';",
    "      for(var di = 0; di < s.domains.length; di++) {",
    "        var d = s.domains[di];",
    "        html += '<div class=\"wizard-domain-row\" data-domain-idx=\"' + di + '\">';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label>Domain</label>';",
    "        html += '<input type=\"text\" class=\"domain-input\" value=\"' + d.domain.replace(/\"/g, '&quot;') + '\" placeholder=\"e.g., watch.sling.com\">';",
    "        html += '</div>';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label>Provider Name</label>';",
    "        html += '<input type=\"text\" class=\"provider-input\" value=\"' + d.provider.replace(/\"/g, '&quot;') + '\" placeholder=\"e.g., Sling TV\">';",
    "        html += '</div>';",
    "        html += '<div class=\"field-group\">';",
    "        html += '<label>Provider Tag <span style=\"color: var(--text-muted);\">(auto-filled)</span></label>';",
    "        html += '<input type=\"text\" class=\"provider-tag-input\" value=\"' + d.providerTag.replace(/\"/g, '&quot;') +",
    "          '\" placeholder=\"auto-generated\">';",
    "        html += '<div class=\"field-hint\">Identifier for the provider filter. Auto-generated from provider name.</div>';",
    "        html += '</div>';",
    "        html += '</div>';",
    "      }",
    "      html += '<button type=\"button\" class=\"wizard-add-domain\" onclick=\"addWizardDomain()\">+ Add another domain</button>';",
    "    }",

    // Step 5: Review and Save.
    "    if(s.currentStep === 5) {",
    "      html += '<label>Review</label>';",
    "      html += '<table class=\"wizard-review-table\">';",
    "      html += '<tr><td>Profile</td><td>' + esc(s.profileName) + '</td></tr>';",
    "      html += '<tr><td>Extends</td><td>' + esc(s.baseProfile) + '</td></tr>';",
    "      html += '<tr><td>Strategy</td><td>' + esc(s.strategy) + '</td></tr>';",
    "      var domainList = s.domains.filter(function(d) { return d.domain; }).map(function(d) { return esc(d.domain); }).join(', ');",
    "      html += '<tr><td>Domain(s)</td><td>' + (domainList || 'none') + '</td></tr>';",
    "      var providerList = s.domains.filter(function(d) { return d.provider; }).map(function(d) { return esc(d.provider); }).join(', ');",
    "      html += '<tr><td>Provider</td><td>' + (providerList || 'none') + '</td></tr>';",
    "      if(s.strategy !== 'none') {",
    "        var reviewStrat = window.__wizardStrategies.find(function(st) { return st.id === s.strategy; });",
    "        if(reviewStrat) {",
    "          for(var ri = 0; ri < reviewStrat.fields.length; ri++) {",
    "            var rf = reviewStrat.fields[ri];",
    "            var rv = s.strategyFields[rf.id];",
    "            if(rf.type === 'text' && rv) {",
    "              html += '<tr><td>' + esc(rf.label.replace(/ \\(CSS\\)/, '')) + '</td><td><code>' + esc(rv) + '</code></td></tr>';",
    "            } else if(rf.type === 'boolean' && rv) {",
    "              html += '<tr><td>' + esc(rf.label) + '</td><td>Yes</td></tr>';",
    "            }",
    "          }",
    "        }",
    "      }",
    "      var flagNames = Object.keys(s.flags).filter(function(k) { return s.flags[k]; });",
    "      if(flagNames.length > 0) {",
    "        html += '<tr><td>Flags</td><td>' + esc(flagNames.join(', ')) + '</td></tr>';",
    "      }",
    "      if(s.hideSelector) html += '<tr><td>Hide Selector</td><td><code>' + esc(s.hideSelector) + '</code></td></tr>';",
    "      html += '</table>';",
    "      html += '<div class=\"field-group\" style=\"margin-top: 16px;\">';",
    "      html += '<label for=\"wizard-description\">Description <span style=\"color: var(--text-muted);\">(optional)</span></label>';",
    "      html += '<textarea id=\"wizard-description\" placeholder=\"Optional description for documentation.\">' + esc(s.description) + '</textarea>';",
    "      html += '</div>';",
    "    }",

    "    content.innerHTML = html;",

    // Attach live event handlers after rendering.
    "    attachWizardHandlers();",
    "  }",

    // Attach event handlers to dynamically rendered wizard inputs.
    "  function attachWizardHandlers() {",
    "    var s = wizardState;",

    // Step 1: profile name and base profile radio.
    "    var nameInput = document.getElementById('wizard-profile-name');",
    "    if(nameInput) nameInput.addEventListener('input', function() { s.profileName = this.value; });",
    "    var radios = document.querySelectorAll('input[name=\"baseProfile\"]');",
    "    for(var i = 0; i < radios.length; i++) {",
    "      radios[i].addEventListener('change', function() { s.baseProfile = this.value; });",
    "    }",

    // Step 2: strategy radio and strategy field inputs. Text and boolean fields are bound by data-field attribute.
    "    var stratRadios = document.querySelectorAll('input[name=\"strategy\"]');",
    "    for(var i = 0; i < stratRadios.length; i++) {",
    "      stratRadios[i].addEventListener('change', function() { s.strategy = this.value; renderWizardStep(); });",
    "    }",
    "    var sfTextInputs = document.querySelectorAll('#wizard-content input[type=\"text\"][data-field]');",
    "    for(var i = 0; i < sfTextInputs.length; i++) {",
    "      sfTextInputs[i].addEventListener('input', function() { s.strategyFields[this.getAttribute('data-field')] = this.value; });",
    "    }",
    "    var sfCheckInputs = document.querySelectorAll('#wizard-content input[type=\"checkbox\"][data-field]');",
    "    for(var i = 0; i < sfCheckInputs.length; i++) {",
    "      sfCheckInputs[i].addEventListener('change', function() {",
    "        if(this.checked) { s.strategyFields[this.getAttribute('data-field')] = true; }",
    "        else { delete s.strategyFields[this.getAttribute('data-field')]; }",
    "      });",
    "    }",

    // Step 3: flag checkboxes and hide selector.
    "    var flagCbs = document.querySelectorAll('input[name^=\"flag-\"]');",
    "    for(var i = 0; i < flagCbs.length; i++) {",
    "      flagCbs[i].addEventListener('change', function() {",
    "        var flagName = this.name.replace('flag-', '');",
    "        if(this.checked) { s.flags[flagName] = true; } else { delete s.flags[flagName]; }",
    "      });",
    "    }",
    "    var hideInput = document.getElementById('wizard-hide-selector');",
    "    if(hideInput) hideInput.addEventListener('input', function() { s.hideSelector = this.value; });",

    // Step 4: domain inputs with auto-fill for provider tag.
    "    var domainRows = document.querySelectorAll('.wizard-domain-row');",
    "    for(var i = 0; i < domainRows.length; i++) {",
    "      (function(idx) {",
    "        var row = domainRows[idx];",
    "        var domInput = row.querySelector('.domain-input');",
    "        var provInput = row.querySelector('.provider-input');",
    "        var tagInput = row.querySelector('.provider-tag-input');",
    "        if(domInput) domInput.addEventListener('input', function() { s.domains[idx].domain = this.value; });",
    "        if(provInput) provInput.addEventListener('input', function() {",
    "          s.domains[idx].provider = this.value;",
    "          var tag = autoProviderTag(this.value);",
    "          s.domains[idx].providerTag = tag;",
    "          if(tagInput) tagInput.value = tag;",
    "        });",
    "        if(tagInput) tagInput.addEventListener('input', function() { s.domains[idx].providerTag = this.value; });",
    "      })(i);",
    "    }",

    // Step 5: description textarea.
    "    var descInput = document.getElementById('wizard-description');",
    "    if(descInput) descInput.addEventListener('input', function() { s.description = this.value; });",
    "  }",

    // Open the wizard modal and reset state.
    "  window.openWizard = function() {",
    "    wizardState = {",
    "      currentStep: 1, editKey: null, editMode: false, highestStep: 1, profileName: '', baseProfile: '', strategy: 'none',",
    "      strategyFields: {}, flags: {}, hideSelector: '',",
    "      domains: [{ domain: '', provider: '', providerTag: '' }], description: ''",
    "    };",
    "    var title = document.getElementById('wizard-title');",
    "    if(title) title.textContent = 'New Provider Profile';",
    "    document.getElementById('wizard-modal').style.display = 'flex';",
    "    renderWizardStep();",
    "  };",

    // Close the wizard modal.
    "  window.closeWizard = function() {",
    "    document.getElementById('wizard-modal').style.display = 'none';",
    "  };",

    // Add another domain row.
    "  window.addWizardDomain = function() {",
    "    wizardState.domains.push({ domain: '', provider: '', providerTag: '' });",
    "    renderWizardStep();",
    "  };",

    // Validate current step. Returns error message or empty string.
    "  function validateStep() {",
    "    var s = wizardState;",
    "    if(s.currentStep === 1) {",
    "      if(!s.editMode) {",
    "        if(!s.profileName.trim()) return 'Profile name is required.';",
    "        if(!/^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?$/.test(s.profileName))",
    "          return 'Must start with a letter, contain only letters, numbers, and hyphens, and not end with a hyphen.';",
    "        if(s.profileName.length > 50) return 'Profile name must be 50 characters or less.';",
    "      }",
    "      if(!s.baseProfile) return 'Select a base profile.';",
    "    }",
    "    if(s.currentStep === 2) {",
    "      var valStrat = window.__wizardStrategies.find(function(st) { return st.id === s.strategy; });",
    "      if(valStrat) {",
    "        for(var vi = 0; vi < valStrat.fields.length; vi++) {",
    "          var vf = valStrat.fields[vi];",
    "          if(vf.required && (vf.type === 'text') && !(s.strategyFields[vf.id] || '').trim()) {",
    "            return vf.label.replace(/ \\(CSS\\)/, '') + ' is required for the ' + valStrat.name + ' strategy.';",
    "          }",
    "        }",
    "      }",
    "    }",
    "    if(s.currentStep === 4) {",
    "      var hasDomain = s.domains.some(function(d) { return d.domain.trim(); });",
    "      if(!hasDomain) return 'At least one domain is required.';",
    "    }",
    "    return '';",
    "  }",

    // Navigate to next step.
    "  window.wizardNext = function() {",
    "    var err = validateStep();",
    "    var errDiv = document.getElementById('wizard-error');",
    "    if(err) {",
    "      errDiv.textContent = err;",
    "      errDiv.style.display = 'block';",
    "      return;",
    "    }",
    "    if(wizardState.currentStep < 5) {",
    "      wizardState.currentStep++;",
    "      if(wizardState.currentStep > wizardState.highestStep) wizardState.highestStep = wizardState.currentStep;",
    "      renderWizardStep();",
    "    }",
    "  };",

    // Navigate to previous step.
    "  window.wizardBack = function() {",
    "    if(wizardState.currentStep > 1) {",
    "      wizardState.currentStep--;",
    "      renderWizardStep();",
    "    }",
    "  };",

    // Navigate to a specific step by clicking the step indicator. Going backward is always allowed for visited steps. Going forward requires validation of the
    // current step and can only reach steps that have been visited before (up to highestStep).
    "  function wizardGoToStep(targetStep) {",
    "    if(targetStep === wizardState.currentStep) return;",
    "    if(targetStep > wizardState.highestStep) return;",
    "    if(targetStep > wizardState.currentStep) {",
    "      var err = validateStep();",
    "      if(err) {",
    "        var errDiv = document.getElementById('wizard-error');",
    "        errDiv.textContent = err;",
    "        errDiv.style.display = 'block';",
    "        return;",
    "      }",
    "    }",
    "    wizardState.currentStep = targetStep;",
    "    renderWizardStep();",
    "  }",

    // Save the profile to the server.
    "  window.saveProfile = function(andTest) {",
    "    var s = wizardState;",
    "    var profile = { extends: s.baseProfile };",
    "    if(s.strategy !== 'none') {",
    "      var cs = { strategy: s.strategy };",
    "      var saveStrat = window.__wizardStrategies.find(function(st) { return st.id === s.strategy; });",
    "      if(saveStrat) {",
    "        for(var si = 0; si < saveStrat.fields.length; si++) {",
    "          var sf = saveStrat.fields[si];",
    "          var sfVal = s.strategyFields[sf.id];",
    "          if(sf.type === 'text' && sfVal) { cs[sf.id] = sfVal; }",
    "          else if(sf.type === 'boolean' && sfVal) { cs[sf.id] = true; }",
    "        }",
    "      }",
    "      profile.channelSelection = cs;",
    "    }",
    "    var flagKeys = Object.keys(s.flags).filter(function(k) { return s.flags[k]; });",
    "    for(var i = 0; i < flagKeys.length; i++) { profile[flagKeys[i]] = true; }",
    "    if(s.hideSelector) profile.hideSelector = s.hideSelector;",
    "    if(s.description) profile.description = s.description;",
    "    var domains = {};",
    "    for(var i = 0; i < s.domains.length; i++) {",
    "      var d = s.domains[i];",
    "      if(d.domain.trim()) {",
    "        domains[d.domain.trim()] = { profile: s.profileName };",
    "        if(d.provider.trim()) domains[d.domain.trim()].provider = d.provider.trim();",
    "        if(d.providerTag.trim()) domains[d.domain.trim()].providerTag = d.providerTag.trim();",
    "      }",
    "    }",
    "    var body = { domains: domains, key: s.profileName, profile: profile };",
    "    fetch('/config/profiles', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify(body)",
    "    })",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        if(data.success) {",
    "          closeWizard();",
    "          if(andTest && s.domains[0] && s.domains[0].domain) {",
    "            startProfileTest(s.domains[0].domain);",
    "          } else {",
    "            location.reload();",
    "          }",
    "        } else {",
    "          var errDiv = document.getElementById('wizard-error');",
    "          errDiv.textContent = data.error || 'Failed to save profile.';",
    "          errDiv.style.display = 'block';",
    "        }",
    "      })",
    "      .catch(function() {",
    "        var errDiv = document.getElementById('wizard-error');",
    "        errDiv.textContent = 'Request failed.';",
    "        errDiv.style.display = 'block';",
    "      });",
    "  };",

    // Test flow: open a browser to a URL with the profile applied and allow selector checking.
    "  var testSelectors = {};",

    // Start a profile test by opening the browser to a URL.
    "  window.startProfileTest = function(url) {",
    "    var s = wizardState;",
    "    testSelectors = {};",
    "    if(s.strategy !== 'none' && s.strategyFields.matchSelector) testSelectors.matchSelector = s.strategyFields.matchSelector;",
    "    if(s.strategyFields.playSelector) testSelectors.playSelector = s.strategyFields.playSelector;",
    "    if(s.hideSelector) testSelectors.hideSelector = s.hideSelector;",
    "    var testUrl = url.indexOf('://') === -1 ? 'https://' + url : url;",
    "    fetch('/config/profiles/test', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify({ url: testUrl })",
    "    })",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        if(data.success) {",
    "          document.getElementById('test-modal').style.display = 'flex';",
    "          document.getElementById('test-selector-results').style.display = 'none';",
    "          document.getElementById('test-check-btn').style.display = ",
    "            Object.keys(testSelectors).length > 0 ? '' : 'none';",
    "        } else {",
    "          showToast('Failed to start test: ' + (data.error || 'Unknown error.'), 'error');",
    "        }",
    "      })",
    "      .catch(function() { showToast('Failed to start test.', 'error'); });",
    "  };",

    // Check CSS selectors against the live page.
    "  window.checkSelectors = function() {",
    "    if(Object.keys(testSelectors).length === 0) return;",
    "    fetch('/config/profiles/test/check', {",
    "      method: 'POST',",
    "      headers: { 'Content-Type': 'application/json' },",
    "      body: JSON.stringify({ selectors: testSelectors })",
    "    })",
    "      .then(function(r) { return r.json(); })",
    "      .then(function(data) {",
    "        var resultsDiv = document.getElementById('test-selector-results');",
    "        if(!data.success || !data.results) {",
    "          resultsDiv.innerHTML = '<p style=\"color: var(--status-error-text);\">Check failed.</p>';",
    "          resultsDiv.style.display = 'block';",
    "          return;",
    "        }",
    "        var html = '<table style=\"width: 100%; font-size: 13px; margin: 12px 0;\">';",
    "        var names = Object.keys(data.results);",
    "        for(var i = 0; i < names.length; i++) {",
    "          var name = names[i];",
    "          var r = data.results[name];",
    "          var color = r.valid && r.count > 0 ? 'var(--status-success-text)' : 'var(--status-error-text)';",
    "          var text = !r.valid ? 'Invalid selector' : r.count + ' element(s)';",
    "          html += '<tr><td style=\"padding: 4px 8px;\">' + esc(name) + '</td>';",
    "          html += '<td style=\"padding: 4px 8px; color: ' + color + ';\">' + text + '</td></tr>';",
    "        }",
    "        html += '</table>';",
    "        resultsDiv.innerHTML = html;",
    "        resultsDiv.style.display = 'block';",
    "      })",
    "      .catch(function() {",
    "        var resultsDiv = document.getElementById('test-selector-results');",
    "        resultsDiv.innerHTML = '<p style=\"color: var(--status-error-text);\">Check request failed.</p>';",
    "        resultsDiv.style.display = 'block';",
    "      });",
    "  };",

    // End the test flow and close the test dialog.
    "  window.endProfileTest = function() {",
    "    fetch('/config/profiles/test/done', { method: 'POST' })",
    "      .then(function() {",
    "        document.getElementById('test-modal').style.display = 'none';",
    "        location.reload();",
    "      })",
    "      .catch(function() {",
    "        document.getElementById('test-modal').style.display = 'none';",
    "      });",
    "  };",

    // Initialize channels subtab on load: hash > localStorage > default.
    "  var initialSubtab = window.initialChannelsHashSubtab;",
    "  if(!initialSubtab) {",
    "    try { initialSubtab = localStorage.getItem('prismcast-channels-subtab'); } catch(e) {}",
    "  }",
    "  if(initialSubtab && document.querySelector('.channels-subtab-btn[data-channels-subtab=\"' + initialSubtab + '\"]')) {",
    "    switchChannelsSubtab(initialSubtab, false);",
    "  }",

    "})();",
    "</script>"
  ].join("\n");
}
