/* Copyright(C) 2024-2026, HJD (https://github.com/hjdhjd). All rights reserved.
 *
 * status.ts: Client-side JavaScript generator for the PrismCast status display.
 */

export function generateStatusScript(): string {

  return [
    "<script>",
    "var statusEventSource = null;",
    "var streamData = {};",
    "var systemData = null;",
    "var expandedStreams = {};",
    "var healthColorVars = { healthy: 'var(--stream-healthy)', buffering: 'var(--stream-buffering)', recovering: 'var(--stream-recovering)', ",
    "  stalled: 'var(--stream-stalled)', error: 'var(--stream-error)' };",

    // Format duration in human readable format.
    "function formatDuration(seconds) {",
    "  if (seconds < 60) return seconds + 's';",
    "  if (seconds < 3600) return Math.floor(seconds / 60) + 'm ' + (seconds % 60) + 's';",
    "  var h = Math.floor(seconds / 3600);",
    "  var m = Math.floor((seconds % 3600) / 60);",
    "  return h + 'h ' + m + 'm';",
    "}",

    // Format bytes in human readable format.
    "function formatBytes(bytes) {",
    "  if (bytes === 0) return '0 B';",
    "  if (bytes < 1024) return bytes + ' B';",
    "  if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';",
    "  return (bytes / 1048576).toFixed(1) + ' MB';",
    "}",

    // Format absolute time (e.g., "6:54 AM" or "Jan 14, 6:54 AM" if different day).
    "function formatTime(isoString) {",
    "  var date = new Date(isoString);",
    "  var now = new Date();",
    "  var hours = date.getHours();",
    "  var minutes = date.getMinutes();",
    "  var ampm = hours >= 12 ? 'PM' : 'AM';",
    "  hours = hours % 12;",
    "  hours = hours ? hours : 12;",
    "  var timeStr = hours + ':' + (minutes < 10 ? '0' : '') + minutes + ' ' + ampm;",
    "  if (date.toDateString() !== now.toDateString()) {",
    "    var months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];",
    "    timeStr = months[date.getMonth()] + ' ' + date.getDate() + ', ' + timeStr;",
    "  }",
    "  return timeStr;",
    "}",

    // Extract concise domain from URL for display (last two hostname parts). Mirrors the server-side extractDomain() in utils/format.ts.
    "function getDomain(url) {",
    "  try {",
    "    var parts = new URL(url).hostname.split('.');",
    "    return parts.length > 2 ? parts.slice(-2).join('.') : parts.join('.');",
    "  } catch (e) {",
    "    return url;",
    "  }",
    "}",

    // Build channel display HTML with an optional logo image. When a logo URL is available, renders an img element with an onerror fallback that hides the
    // image and reveals a text span. The logoClass and textClass parameters allow callers to apply context-specific sizing.
    "function channelDisplayHtml(logoUrl, name, logoClass, textClass) {",
    "  if(logoUrl) {",
    "    return '<img src=\"' + logoUrl + '\" class=\"' + logoClass + '\" alt=\"' + name + '\" title=\"' + name + '\" ' +",
    "      'onerror=\"this.style.display=\\'none\\';this.nextElementSibling.style.display=\\'inline\\'\">' +",
    "      '<span class=\"' + textClass + '\" style=\"display:none\">' + name + '</span>';",
    "  }",
    "  return '<span class=\"' + textClass + '\">' + name + '</span>';",
    "}",

    // Get row background color based on health status. Uses CSS variables for theme support.
    "function getRowTint(health) {",
    "  var tints = {",
    "    healthy: 'transparent',",
    "    buffering: 'var(--stream-tint-buffering)',",
    "    stalled: 'var(--stream-tint-stalled)',",
    "    recovering: 'var(--stream-tint-recovering)',",
    "    error: 'var(--stream-tint-error)'",
    "  };",
    "  return tints[health] || 'transparent';",
    "}",

    // Get health badge HTML using CSS variables for theme-aware colors. NOTE: Escalation level semantics defined in monitor.ts.
    // L1=play/unmute, L2=seek, L3=source reload, L4=page navigation.
    "function getHealthBadge(health, level) {",
    "  var label = '';",
    "  if (health === 'healthy') { label = 'Healthy'; }",
    "  else if (health === 'buffering') { label = 'Buffering'; }",
    "  else if (health === 'stalled') { label = 'Stalled'; }",
    "  else if (health === 'error') { label = 'Error'; }",
    "  else if (health === 'recovering') {",
    "    if (level === 1) { label = 'Resuming playback'; }",
    "    else if (level === 2) { label = 'Syncing to live'; }",
    "    else if (level === 3) { label = 'Reloading player'; }",
    "    else if (level >= 4) { label = 'Reloading page'; }",
    "    else { label = 'Recovering'; }",
    "  }",
    "  else { label = health; }",
    "  return '<span class=\"status-dot\" style=\"color: ' + (healthColorVars[health] || 'var(--text-muted)') + ';\">&#9679;</span> ' +",
    "    '<span style=\"color: var(--text-secondary);\">' + label + '</span>';",
    "}",

    // Update system status display in header. Shows system health (green dot when connected, red with label when not) and stream count.
    "function updateSystemStatus() {",
    "  if(!systemData) return;",
    "  var healthEl = document.getElementById('system-health');",
    "  var streamEl = document.getElementById('stream-count');",
    "  if(systemData.browser.connected) {",
    "    healthEl.innerHTML = '<span class=\"status-dot\" style=\"color: var(--stream-healthy);\">&#9679;</span>';",
    "  } else {",
    "    healthEl.innerHTML = '<span class=\"status-dot\" style=\"color: var(--stream-error);\">&#9679;</span> Browser offline';",
    "  }",
    "  var active = systemData.streams.active;",
    "  var limit = systemData.streams.limit;",
    "  if(active === 0) {",
    "    streamEl.textContent = '0 streams';",
    "    streamEl.classList.remove('clickable');",
    "    var popMenu = document.getElementById('stream-popover-menu');",
    "    if(popMenu) popMenu.classList.remove('show');",
    "  } else {",
    "    streamEl.textContent = active + '/' + limit + ' streams';",
    "    streamEl.classList.add('clickable');",
    "  }",
    "}",

    // Build the popover content from streamData. Populates the given menu element with one row per active stream.
    "function buildStreamPopoverContent(menu) {",
    "  var ids = Object.keys(streamData);",
    "  var html = '';",
    "  var now = Date.now();",
    "  for(var i = 0; i < ids.length; i++) {",
    "    var s = streamData[ids[i]];",
    "    var color = healthColorVars[s.health] || 'var(--text-muted)';",
    "    var name = s.channel || s.providerName || getDomain(s.url);",
    "    var dur = Math.floor((now - new Date(s.startTime).getTime()) / 1000);",
    "    var showSuffix = s.showName ? ' <span class=\"stream-popover-show\">' + s.showName + '</span>' : '';",
    "    html += '<div class=\"stream-popover-row\">';",
    "    html += '<span class=\"status-dot\" style=\"color: ' + color + ';\">&#9679;</span>';",
    "    html += channelDisplayHtml(s.logoUrl, name, 'stream-popover-logo', 'stream-popover-channel');",
    "    html += showSuffix;",
    "    html += '<span class=\"stream-popover-duration\">' + formatDuration(dur) + '</span>';",
    "    html += '</div>';",
    "  }",
    "  menu.innerHTML = html;",
    "}",

    // Update an already-open stream popover with current data. Called from SSE handlers and the duration interval.
    "function updateStreamPopover() {",
    "  var menu = document.getElementById('stream-popover-menu');",
    "  if(!menu || !menu.classList.contains('show')) return;",
    "  var ids = Object.keys(streamData);",
    "  if(ids.length === 0) {",
    "    menu.classList.remove('show');",
    "    return;",
    "  }",
    "  buildStreamPopoverContent(menu);",
    "}",

    // Toggle the stream popover open or closed.
    "window.toggleStreamPopover = function() {",
    "  var ids = Object.keys(streamData);",
    "  if(ids.length === 0) return;",
    "  var menu = document.getElementById('stream-popover-menu');",
    "  if(!menu) return;",
    "  var isOpen = menu.classList.contains('show');",
    "  closeDropdowns();",
    "  if(!isOpen) {",
    "    buildStreamPopoverContent(menu);",
    "    menu.classList.add('show');",
    "  }",
    "};",

    // Format last issue for display.
    "function formatLastIssue(s) {",
    "  if (!s.lastIssueType || !s.lastIssueTime) { return 'None'; }",
    "  var issueLabel = s.lastIssueType.charAt(0).toUpperCase() + s.lastIssueType.slice(1);",
    "  var timeStr = formatTime(new Date(s.lastIssueTime).toISOString());",
    "  var status = (s.health === 'healthy') ? ' (recovered)' : ' (recovering)';",
    "  return issueLabel + ' at ' + timeStr + status;",
    "}",

    // Format auto-recovery info for display.
    "function formatAutoRecovery(s) {",
    "  var attempts = s.recoveryAttempts;",
    "  var reloads = s.pageReloadsInWindow;",
    "  if (attempts === 0) { return 'N/A'; }",
    "  var str = attempts + (attempts === 1 ? ' attempt' : ' attempts');",
    "  if (reloads > 0) { str += ', ' + reloads + (reloads === 1 ? ' page reload' : ' page reloads'); }",
    "  return str;",
    "}",

    // Format client type breakdown for the detail row.
    "function formatClients(s) {",
    "  if (s.clientCount === 0) { return 'None'; }",
    "  var labels = { 'hls': 'HLS', 'mpegts': 'MPEG-TS' };",
    "  var parts = [];",
    "  for (var i = 0; i < s.clients.length; i++) {",
    "    var c = s.clients[i];",
    "    parts.push(c.count + ' ' + (labels[c.type] || c.type));",
    "  }",
    "  return parts.join(', ');",
    "}",

    // Render the streams table.
    "function renderStreamsTable() {",
    "  var tbody = document.getElementById('streams-tbody');",
    "  if (!tbody) return;",
    "  var streamIds = Object.keys(streamData);",
    "  if (streamIds.length === 0) {",
    "    tbody.innerHTML = '<tr class=\"empty-row\"><td colspan=\"4\">No active streams</td></tr>';",
    "    return;",
    "  }",
    "  var html = '';",
    "  for (var i = 0; i < streamIds.length; i++) {",
    "    var id = streamIds[i];",
    "    var s = streamData[id];",
    "    var isExpanded = expandedStreams[id];",
    "    var chevron = isExpanded ? '&#9660;' : '&#9654;';",
    "    var rowTint = getRowTint(s.health);",
    "    var channelText = s.channel || s.providerName || getDomain(s.url);",
    "    var channelDisplay = channelDisplayHtml(s.logoUrl, channelText, 'channel-logo', 'channel-text');",
    "    html += '<tr class=\"stream-row\" data-id=\"' + id + '\" onclick=\"toggleStreamDetails(' + id + ')\" style=\"background-color: ' + rowTint + ';\">';",
    "    html += '<td class=\"chevron\">' + chevron + '</td>';",
    "    var durationSpan = '<span class=\"stream-duration\" id=\"duration-' + id + '\">\\u00b7 ' + formatDuration(s.duration) + '</span>';",
    "    html += '<td class=\"stream-info\">' + channelDisplay + ' ' + durationSpan + '</td>';",
    "    var showDisplay = s.showName ? s.showName : '';",
    "    html += '<td class=\"stream-show\">' + showDisplay + '</td>';",
    "    var clientIndicator = '';",
    "    if (s.clientCount > 0) {",
    "      var title = s.clientCount + (s.clientCount !== 1 ? ' clients' : ' client');",
    "      clientIndicator = '<span class=\"client-count\" title=\"' + title + '\">&#9673; ' + s.clientCount + '</span> ';",
    "    }",
    "    html += '<td class=\"stream-health\">' + clientIndicator + getHealthBadge(s.health, s.escalationLevel) + '</td>';",
    "    html += '</tr>';",
    "    if (isExpanded) {",
    "      html += '<tr class=\"stream-details\" data-id=\"' + id + '\">';",
    "      html += '<td colspan=\"4\">';",
    "      html += '<div class=\"details-content\">';",
    "      html += '<div class=\"details-header\">';",
    "      html += '<div class=\"details-url\">' + s.url + '</div>';",
    "      var clientSuffix = s.clientCount > 0 ? ' &middot; ' + formatClients(s) : '';",
    "      html += '<div class=\"details-started\"><strong>Started:</strong> ' + formatTime(s.startTime) + clientSuffix + '</div>';",
    "      html += '</div>';",
    "      html += '<div class=\"details-metrics\">';",
    "      html += '<div class=\"details-issue\"><strong>Last issue:</strong> ' + formatLastIssue(s) + '</div>';",
    "      html += '<div class=\"details-recovery\"><strong>Recovery:</strong> ' + formatAutoRecovery(s) + '</div>';",
    "      html += '<div class=\"details-memory\"><strong>Memory:</strong> ' + formatBytes(s.memoryBytes) + '</div>';",
    "      html += '</div>';",
    "      html += '</div>';",
    "      html += '</td></tr>';",
    "    }",
    "  }",
    "  tbody.innerHTML = html;",
    "}",

    // Toggle stream details.
    "function toggleStreamDetails(id) {",
    "  expandedStreams[id] = !expandedStreams[id];",
    "  renderStreamsTable();",
    "}",

    // Update stream durations every second. We calculate duration from the immutable startTime rather than incrementing a counter, ensuring the displayed duration is
    // always accurate regardless of any staleness in server-sent updates.
    "function updateDurations() {",
    "  var now = Date.now();",
    "  var streamIds = Object.keys(streamData);",
    "  for (var i = 0; i < streamIds.length; i++) {",
    "    var id = streamIds[i];",
    "    var s = streamData[id];",
    "    var durationSec = Math.floor((now - new Date(s.startTime).getTime()) / 1000);",
    "    var el = document.getElementById('duration-' + id);",
    "    if (el) el.textContent = '\\u00b7 ' + formatDuration(durationSec);",
    "  }",
    "  updateStreamPopover();",
    "}",

    // Track the last time any SSE event was received from the status stream. Used by the staleness checker to detect silently dead connections.
    "var lastStatusEventTime = Date.now();",
    "var hiddenSince = 0;",

    // Real-time health indicator updates. These functions update channel health icons and provider login icons in the Channels tab without a page refresh.
    "function formatTimeAgo(ts) {",
    "  var seconds = Math.floor((Date.now() - ts) / 1000);",
    "  if(seconds < 60) { return 'just now'; }",
    "  var minutes = Math.floor(seconds / 60);",
    "  if(minutes < 60) { return minutes + (minutes === 1 ? ' minute ago' : ' minutes ago'); }",
    "  var hours = Math.floor(minutes / 60);",
    "  if(hours < 24) { return hours + (hours === 1 ? ' hour ago' : ' hours ago'); }",
    "  var days = Math.floor(hours / 24);",
    "  return days + (days === 1 ? ' day ago' : ' days ago');",
    "}",
    "function updateChannelHealth(channelKey, status, timestamp, providerTag) {",
    "  var row = document.getElementById('display-row-' + channelKey);",
    "  if(!row) { return; }",

    // If a providerTag was supplied (snapshot and real-time events both include it), verify it matches the currently selected provider for this channel. The login
    // button carries a data-provider-tag attribute with the selected provider. If the tags differ the health entry is from a previous provider and should be ignored.
    "  if(providerTag) {",
    "    var loginBtn = row.querySelector('.btn-icon-login');",
    "    if(loginBtn && loginBtn.getAttribute('data-provider-tag') !== providerTag) { return; }",
    "  }",
    "  var icon = row.querySelector('.btn-icon-health');",
    "  if(!icon) { return; }",
    "  icon.classList.remove('health-success', 'health-failed');",
    "  if(status === 'success') { icon.classList.add('health-success'); }",
    "  else if(status === 'failed') { icon.classList.add('health-failed'); }",
    "  icon.title = (status === 'success' ? 'Succeeded ' : 'Failed ') + formatTimeAgo(timestamp);",
    "}",
    "function updateProviderAuth(providerTag, timestamp) {",
    "  var buttons = document.querySelectorAll('.btn-icon-login[data-provider-tag=\"' + providerTag + '\"]');",
    "  for(var i = 0; i < buttons.length; i++) {",
    "    buttons[i].classList.add('health-success');",
    "    buttons[i].title = 'Verified ' + formatTimeAgo(timestamp);",
    "  }",
    "}",
    "function applyHealthSnapshot(data) {",
    "  var key;",
    "  for(key in data.channels) {",
    "    var entry = data.channels[key];",
    "    updateChannelHealth(key, entry.status, entry.timestamp, entry.providerTag);",
    "  }",
    "  for(key in data.providers) {",
    "    updateProviderAuth(key, data.providers[key]);",
    "  }",
    "}",

    // Connect (or reconnect) to the status SSE stream. Closes any existing connection first so this is safe to call repeatedly.
    "function connectStatusSSE() {",
    "  if(statusEventSource) { statusEventSource.close(); }",
    "  statusEventSource = new EventSource('/streams/status');",
    "  lastStatusEventTime = Date.now();",

    // Local helper that registers an event listener and updates the staleness timestamp on every event. Handlers are optional so heartbeat can
    // be registered with just on('heartbeat') for pure keepalive tracking. The onerror handler stays outside this wrapper because errors must
    // not reset the staleness timer — a connection that only fires errors is still dead.
    "  function on(event, handler) {",
    "    statusEventSource.addEventListener(event, function(e) {",
    "      lastStatusEventTime = Date.now();",
    "      if(handler) { handler(e); }",
    "    });",
    "  }",
    "  on('heartbeat');",
    "  on('snapshot', function(e) {",
    "    var data = JSON.parse(e.data);",
    "    systemData = data.system;",
    "    streamData = {};",
    "    for (var i = 0; i < data.streams.length; i++) {",
    "      streamData[data.streams[i].id] = data.streams[i];",
    "    }",
    "    updateSystemStatus();",
    "    renderStreamsTable();",
    "    updateStreamPopover();",
    "    if(data.health) { applyHealthSnapshot(data.health); }",
    "  });",
    "  on('streamAdded', function(e) {",
    "    var s = JSON.parse(e.data);",
    "    streamData[s.id] = s;",
    "    renderStreamsTable();",
    "    updateStreamPopover();",
    "  });",
    "  on('streamRemoved', function(e) {",
    "    var data = JSON.parse(e.data);",
    "    delete streamData[data.id];",
    "    delete expandedStreams[data.id];",
    "    renderStreamsTable();",
    "    updateStreamPopover();",
    "    if (typeof updateRestartDialogStatus === 'function') {",
    "      updateRestartDialogStatus();",
    "    }",
    "  });",
    "  on('streamHealthChanged', function(e) {",
    "    var s = JSON.parse(e.data);",
    "    if (streamData[s.id]) {",
    "      streamData[s.id] = s;",
    "      renderStreamsTable();",
    "      updateStreamPopover();",
    "    }",
    "  });",
    "  on('systemStatusChanged', function(e) {",
    "    systemData = JSON.parse(e.data);",
    "    updateSystemStatus();",
    "  });",
    "  on('healthChanged', function(e) {",
    "    var event = JSON.parse(e.data);",
    "    updateChannelHealth(event.channelKey, event.status, event.timestamp, event.providerTag);",
    "    if(event.status === 'success') { updateProviderAuth(event.providerTag, event.timestamp); }",
    "  });",
    "  statusEventSource.onerror = function() {",
    "    document.getElementById('system-health').innerHTML = '<span class=\"status-dot\" style=\"color: var(--stream-stalled);\">&#9679;</span> Updates paused';",
    "  };",
    "}",

    // Initial connection and periodic timers.
    "connectStatusSSE();",
    "setInterval(updateDurations, 1000);",

    // Staleness detection: if no SSE event has arrived in 45 seconds, the connection is likely dead. Reconnect proactively.
    "setInterval(function() {",
    "  if((Date.now() - lastStatusEventTime) > 45000) { connectStatusSSE(); }",
    "}, 45000);",

    // Visibility-driven reconnect. When the page returns from being hidden for more than 30 seconds, reconnect the status stream and re-activate
    // the current tab so the logs stream reconnects naturally through its existing tabactivated listener.
    "document.addEventListener('visibilitychange', function() {",
    "  if(document.hidden) {",
    "    hiddenSince = Date.now();",
    "  } else if((hiddenSince > 0) && ((Date.now() - hiddenSince) > 30000)) {",
    "    hiddenSince = 0;",
    "    connectStatusSSE();",
    "    var activeTab = document.querySelector('.tab-btn.active');",
    "    if(activeTab) {",
    "      document.dispatchEvent(new CustomEvent('tabactivated', { detail: { category: activeTab.getAttribute('data-category') } }));",
    "    }",
    "  } else {",
    "    hiddenSince = 0;",
    "  }",
    "});",

    // Copy playlist URL function for Overview tab Quick Start section.
    "window.copyOverviewPlaylistUrl = function() {",
    "  var urlEl = document.getElementById('overview-playlist-url');",
    "  if (urlEl) {",
    "    navigator.clipboard.writeText(urlEl.textContent).then(function() {",
    "      var feedback = document.getElementById('overview-copy-feedback');",
    "      if (feedback) {",
    "        feedback.style.display = 'inline';",
    "        setTimeout(function() { feedback.style.display = 'none'; }, 2000);",
    "      }",
    "    });",
    "  }",
    "};",

    // JS-based tooltips for devices where the primary input can't hover (iPadOS). Safari on iPadOS doesn't show native title tooltips, so we use
    // a single <div> appended to <body> and positioned via getBoundingClientRect(). This is immune to overflow containers and stacking contexts.
    // On pure-touch devices without a trackpad, mouseenter never fires so the tooltip stays hidden. Desktop skips initialization entirely.
    "(function() {",
    "  if(!window.matchMedia('(hover: none)').matches) return;",
    "  var tip = document.createElement('div');",
    "  tip.className = 'btn-icon-tooltip';",
    "  document.body.appendChild(tip);",
    "  document.addEventListener('mouseenter', function(e) {",
    "    var btn = e.target.closest('.btn-icon[aria-label]');",
    "    if(!btn) return;",
    "    var label = btn.getAttribute('title') || btn.getAttribute('aria-label');",
    "    if(!label) return;",
    "    var rect = btn.getBoundingClientRect();",
    "    tip.textContent = label;",
    "    tip.classList.add('visible');",
    "    tip.style.top = (rect.bottom + 6) + 'px';",
    "    tip.style.left = (rect.left + rect.width / 2) + 'px';",
    "    tip.style.transform = 'translateX(-50%)';",
    "  }, true);",
    "  document.addEventListener('mouseleave', function(e) {",
    "    var src = e.target.closest('.btn-icon[aria-label]');",
    "    if(!src) return;",
    "    var dest = e.relatedTarget && e.relatedTarget.closest && e.relatedTarget.closest('.btn-icon[aria-label]');",
    "    if(dest === src) return;",
    "    tip.classList.remove('visible');",
    "  }, true);",
    "})();",

    "</script>"
  ].join("\n");
}
